# Chapter 0 : Pytorch Fundamentals

In [98]:
#import necessary libraries
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
x = torch.rand(5, 3)
print(x)

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547]])


In [2]:
#intro to tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#gives us the dimensions
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
#create a vector 
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
#dimensions are defined by the number of [] that exist in the parenthesis
vector.ndim

1

In [7]:
#shape is the number of items in each []
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
#TENSOR
TENSOR= torch.tensor([ [ [1,2,3,4],[4,5,6,5],[7,8,9,5] ] ,[[1,2,3,4], [3,4,5,4], [2,3,4,4] ], ])
TENSOR

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 5],
         [7, 8, 9, 5]],

        [[1, 2, 3, 4],
         [3, 4, 5, 4],
         [2, 3, 4, 4]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([2, 3, 4])

In [22]:
#RANDOM TENSORS

#random tensors are important because the way most neural networks learn is they start with tensors full of random numbers
#and then they adjust those numbers to better represent the data

# the flow is the following start with random numbers -> look at data -> update numbers -> look at data etc...

#create a random tensor that has size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8044, 0.7765, 0.6455, 0.8544],
        [0.8262, 0.9842, 0.9249, 0.3605],
        [0.8711, 0.6080, 0.0809, 0.3386]])

In [23]:
#create a random tensor with similar shape to an image tensor
random_image_tensor=torch.rand(size=(224,224,3)) #height, width colour channel (R, G, B)
random_image_tensor
random_image_tensor.shape, random_image_tensor.ndim 

(torch.Size([224, 224, 3]), 3)

In [25]:
#create a tensor of all zeroes
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
#creating a range of tensors and tensors-like 
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensors datatypes
tensor datatype is one of the 3 big errors we encounter in deep learning 
1. tensor not right datatype
2. tensor not right shape
3. tensor on the right device

In [5]:
#float_32 tensor
float_32_tensor= torch.tensor([1.0,2.0,3.0],
                             dtype=None, #defines the data type of he tensor
                             device=None, #defines the device the tensor is on 
                             requires_grad=False #wether or not to track gradients with this tensors operations
                            )
float_32_tensor

tensor([1., 2., 3.])

In [6]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [7]:
float_32_tensor*float_16_tensor

tensor([1., 4., 9.])

# get information from tensors
1. tensor not right datatype - to get tensors datatype use tensor.dtype
2. tensor not right shape - to get a tensors shape use tensor.shape 
3. tensor on the right device - to get a tensors device use tensor.device

In [8]:
#testing these functions
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5967, 0.7270, 0.4642, 0.9857],
        [0.6219, 0.9651, 0.8151, 0.9666],
        [0.9827, 0.8628, 0.4643, 0.3154]])

In [10]:
print(f"datatype of tensor is {some_tensor.dtype}")

datatype of tensor is torch.float32


In [11]:
print(f"shape of tensor is {some_tensor.shape}")

shape of tensor is torch.Size([3, 4])


In [12]:
print(f"device of tensor is {some_tensor.device}")

device of tensor is cpu


# Manipulating tensors
Common tensor operations : 
1. addition
2. subtraction
3. multiplication
4. division
5. Matric multiplication

In [13]:
#addition
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [14]:
#multiplication
tensor*10

tensor([10, 20, 30])

In [15]:
#subtraction
tensor-10

tensor([-9, -8, -7])

In [16]:
#division
tensor/10

tensor([0.1000, 0.2000, 0.3000])

# Matrix Multiplication
Relative info on hoq multiplication in matrices works : https://www.mathsisfun.com/algebra/matrix-multiplying.html

It needs to satidy 2 conditions :
1. The inner dimesions must match examples
   (3,2) @ (3,2) WONT WORK
   (2,3) @ (3,2) WILL WORK
   (3,2) @ (2,3) WILL WORK
2. The resulting matrix must have the shape of the OUTER dimensions 
   (2,3) @ (3,2) -> (2, 2)

In [17]:
#example
print(f"Result : {tensor * tensor}")

Result : tensor([1, 4, 9])


In [18]:
torch.matmul(tensor,tensor)

tensor(14)

In [5]:
### One of the most common errors in Deep Learning : shape errors
#example
tensor1=torch.tensor([[1,2],
                    [4,5],
                    [7,8]])

tensor2=torch.tensor([[1,2],
                    [4,5],
                    [7,8]])

torch.matmul(tensor1,tensor2)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [6]:
#fixing the issue
tensor1.shape, tensor2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [9]:
#we use a transpose to manipulate the shape of our tensors
#it switches the axes of the dimensions
tensor1.T, tensor1.T.shape

(tensor([[1, 4, 7],
         [2, 5, 8]]),
 torch.Size([2, 3]))

In [10]:
tensor1, tensor1.shape

(tensor([[1, 2],
         [4, 5],
         [7, 8]]),
 torch.Size([3, 2]))

In [12]:
#matrix multiplication works when tensor2 is transpose
torch.matmul(tensor1, tensor2.T), torch.matmul(tensor1, tensor2.T).shape, 

(tensor([[  5,  14,  23],
         [ 14,  41,  68],
         [ 23,  68, 113]]),
 torch.Size([3, 3]))

# Tensor aggragation
Finding min,max,sum,mean value etc..

In [14]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
#find min
x.min()


tensor(0)

In [17]:
#find max
x.max()

tensor(90)

In [21]:
#find mean value
#note that mean function requires a tensor of float32 to work so we have to change the datatype in some cases
x.type(torch.float32).mean()

tensor(45.)

In [22]:
#find the sum
x.sum()

tensor(450)

In [23]:
#find the positional min. this means the position in the tensor where the min value is located
x.argmin()

tensor(0)

In [24]:
#find the positional max. this means the position in the tensor where the max value is located
x.argmax()

tensor(9)

## Reshaping, stacking squeezing and un-squeezing tensors
Reshaping - reshapes an input tensor into a defined shape
View - return a view of an input tensor. Its important to note that the view shares the memory of the original
Stacking - combine multiple tensors on top of each other
Squeeze - removes all '1' dimensions from a tensor
Unsqueeze - adds a '1' dimension to a target tensor
Permute - returns a view of the input with the dimesnions permuted (swapped) a cerain way  

In [35]:
#create a tensor
x=torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [38]:
#add an extra dimension 
#the reshaping has to be compatible with the original size
x_reshaped=x.reshape(5,2)
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [43]:
#change the view
z=x.view(2,5)
z, x

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [45]:
#changing z also changes x because they share the same memory
z[:, 0]=5
z,x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [55]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[[[[0.7804],
           [0.8824]],

          [[0.6983],
           [0.1460]]],


         [[[0.7804],
           [0.8824]],

          [[0.6983],
           [0.1460]]],


         [[[0.7804],
           [0.8824]],

          [[0.6983],
           [0.1460]]],


         [[[0.7804],
           [0.8824]],

          [[0.6983],
           [0.1460]]]]])

In [56]:
x=torch.rand(1,2,2,1)
x, x.shape

(tensor([[[[0.5795],
           [0.0999]],
 
          [[0.0666],
           [0.4159]]]]),
 torch.Size([1, 2, 2, 1]))

In [63]:
#squeeze removes all single dimensions from target tensor
x_squeezed=torch.squeeze(x)
x_squeezed, x_squeezed.shape

(tensor([[0.5795, 0.0999],
         [0.0666, 0.4159]]),
 torch.Size([2, 2]))

In [70]:
#unsqueeze adds a single dimension to a tensor target
print(f"previous target {x_squeezed}")
print(f"previous shape {x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0)

print(f"current target {x_unsqueezed}")
print(f"current shape {x_unsqueezed.shape}")


previous target tensor([[0.5795, 0.0999],
        [0.0666, 0.4159]])
previous shape torch.Size([2, 2])
current target tensor([[[0.5795, 0.0999],
         [0.0666, 0.4159]]])
current shape torch.Size([1, 2, 2])


In [71]:
#permute swaps the dimensions of a given tensor input
#permute is also a view wich means it shares the same memory as the original
#any changes in permuted tensor affect the original 
print(f"previous target {x}")
print(f"previous shape {x.shape}")

x_permuted=x.permute(3,2,0,1)

print(f"current target {x_permuted}")
print(f"current shape {x_permuted.shape}")

previous target tensor([[[[0.5795],
          [0.0999]],

         [[0.0666],
          [0.4159]]]])
previous shape torch.Size([1, 2, 2, 1])
current target tensor([[[[0.5795, 0.0666]],

         [[0.0999, 0.4159]]]])
current shape torch.Size([1, 2, 1, 2])


# Indexing in Pytorch
Its similar to indexing in NumPy

pytorch is compaible with numpy 

* data in numpy, want in pytorch tensor -> torch.from_numpy(ndarray)

* conver pytorch tensor to numpy data -> torch.Tensor.numpy() 

In [73]:
#create example tensor
tensor=torch.arange(1,10).reshape(1,3,3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
#lets index on our new tensor
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
tensor[0, 0]

tensor([1, 2, 3])

In [78]:
tensor[0][0][2]

tensor(3)

In [80]:
#we can use : to select "all" of a target dimension
tensor[: , 0]

tensor([[1, 2, 3]])

In [82]:
#get all the values from 0th and 1st dimension but only index 2 of dimension 2
tensor[:,:,1]

tensor([[2, 5, 8]])

In [83]:
#get all values from 0th dimension but only index 1 from 1st dimension and index 2 from 2nd
tensor[:,0,1]

tensor([2])

In [84]:
#get 1 index from 0th and 1st dimension and all values from 2nd dimension
tensor[0,0,:]

tensor([1, 2, 3])

In [85]:
tensor[0,2,2]

tensor(9)

In [87]:
tensor[0,:,2]

tensor([3, 6, 9])

In [90]:
#data conversion from pytorch to numpy
import torch
import numpy as np

array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducability (take random out of random)
how a neural network learns :
1) Start with random numbers
2) Tensor operations to update random numbers and try to make them better representaions of the data
3) Repeat step 2 constantly

To reduce the randomness in neural netoworks in Pytorch comes the concept of *random seed*. Essentially what it does is **flavour** the randomness

In [93]:
#example of random and unreproducable tensors
import torch 

t_a=torch.rand(3,4)

t_b=torch.rand(3,4)

print(t_a)
print(t_b)
print(t_a==t_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
#lets make some random but reproducable tensors
import torch 

RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
t_c=torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
t_d=torch.rand(3,4)

print(t_c)
print(t_d)
print(t_c==t_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Extra resources for reproducability : https://pytorch.org/docs/stable/notes/randomness.html